// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABJZbPi_Fk1ewBASmJVtXQq2OtJQFJXZo',
    appId: '1:623768590956:web:e05cc076ee3ab22d945649',
    messagingSenderId: '623768590956',
    projectId: 'pixelbank-68bc5',
    authDomain: 'pixelbank-68bc5.firebaseapp.com',
    storageBucket: 'pixelbank-68bc5.firebasestorage.app',
    measurementId: 'G-94E06VD7YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6vKTFiblR9gY1Ud0IftYXQ9PPG1Xf4O8',
    appId: '1:623768590956:android:1b0ed157b407c1a0945649',
    messagingSenderId: '623768590956',
    projectId: 'pixelbank-68bc5',
    storageBucket: 'pixelbank-68bc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBpdsHV7KchGSwGqT5PCT8FFNc_c9xvyk',
    appId: '1:623768590956:ios:b222d28ebed24d73945649',
    messagingSenderId: '623768590956',
    projectId: 'pixelbank-68bc5',
    storageBucket: 'pixelbank-68bc5.firebasestorage.app',
    iosBundleId: 'com.example.bancoDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBpdsHV7KchGSwGqT5PCT8FFNc_c9xvyk',
    appId: '1:623768590956:ios:b222d28ebed24d73945649',
    messagingSenderId: '623768590956',
    projectId: 'pixelbank-68bc5',
    storageBucket: 'pixelbank-68bc5.firebasestorage.app',
    iosBundleId: 'com.example.bancoDigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABJZbPi_Fk1ewBASmJVtXQq2OtJQFJXZo',
    appId: '1:623768590956:web:1ba25dc7545ef3a3945649',
    messagingSenderId: '623768590956',
    projectId: 'pixelbank-68bc5',
    authDomain: 'pixelbank-68bc5.firebaseapp.com',
    storageBucket: 'pixelbank-68bc5.firebasestorage.app',
    measurementId: 'G-DSPMLYSH3W',
  );
}
